---
name: ğŸ§ª Test & Validation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "feature/*"
      - "release/*"
      - "bugfix/*"
      - "hotfix/*"

jobs:
  lint:
    name: ğŸ§ª Lint code
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out the codebase
        uses: actions/checkout@v4

      - name: ğŸ Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Install dependencies
        run: |
          pip3 install yamllint ansible-lint

      - name: ğŸ” Lint code
        run: |
          yamllint .

      - name: ğŸ” Lint Ansible files
        run: |
          ansible-lint

  molecule:
    name: ğŸ§ª Molecule test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        include:
          - scenario: default
            distro: ubuntu2204
          - scenario: default
            distro: ubuntu2404
          - scenario: default
            distro: debian11
          - scenario: default
            distro: debian12

    steps:
      - name: ğŸ“¥ Check out the codebase
        uses: actions/checkout@v4

      - name: ğŸ Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Install dependencies
        run: |
          pip3 install ansible molecule molecule-plugins[docker] docker

      - name: ğŸš€ Run molecule test
        run: |
          molecule test --scenario-name ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
